sudo: required

services:
  - docker
  
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

git:
  depth: 1

branches:
  only:
  - master

language: generic

env:
  - NPM_TAG=latest
  - NPM_TAG=next

install:
  - cd theia-docker
  - IMAGE_TAG=typefox/theia:$(npm view "@theia/core@$NPM_TAG" version)
  - echo $IMAGE_TAG
  - docker pull "$IMAGE_TAG" || true
  - docker build --build-arg "version=$NPM_TAG" . -t "$IMAGE_TAG" --cache-from "$IMAGE_TAG"
  - docker tag "$IMAGE_TAG" "typefox/theia:$NPM_TAG"
  - cd ../theia-java-docker
  - IMAGE_TAG=typefox/theia-java:$(npm view "@theia/core@$NPM_TAG" version)
  - echo $IMAGE_TAG
  - docker pull "$IMAGE_TAG" || true
  - docker build --build-arg "version=$NPM_TAG" . -t "$IMAGE_TAG" --cache-from "$IMAGE_TAG"
  - docker tag "$IMAGE_TAG" "typefox/theia-java:$NPM_TAG"

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push typefox/theia && docker push typefox/theia-java
  on:
    branch: master
  skip_cleanup: true

notifications:
  on_success: change
  on_failure: always
  on_start: never
